version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seguros
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: seguros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"